[package]
name = "orcxx"
version = "0.1.0"
authors = [
    "Software Heritage developers <swh-devel@inria.fr>"
]
rust-version = "1.63"
description = "Rust bindings for the official C++ library for Apache ORC"
readme = "README.md"
homepage = "https://gitlab.softwareheritage.org/swh/devel/orcxx-rs"
repository = "https://gitlab.softwareheritage.org/swh/devel/orcxx-rs"
license = "GPL-3.0-or-later"
keywords = ["orc", "apache-orc"]
categories = ["api-bindings", "encoding", "parser-implementations"]
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
